### ISSUE TITLE
Handle custom openaps directories

### ISSUE THREAD

**Issue by efidoman** [openaps/openaps-menu#2]
How do we plan for these scripts to handle custom (or non "myopenaps") install directories? For now, the scripts hard-code it to /root/myopenaps.

**Comment by scottleibrand** [comment]
Custom directory names are deprecated and have been removed from the interactive oref0-setup. I don't plan to support them in any new features. If anyone insists on sticking with a vanity name, they can modify all the dependencies themselves.

**Comment by efidoman** [comment]
Ok - works for me.
